on:
  pull_request:
    types: [opened, reopened]

name: "Trigger: Pull action"
permissions: {}

jobs:
  typocheck:
    name: Typocheck
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
      - name: Run proselint
        run: pip install proselint
      - run: proselint **/*.md
      - name: Run write-good
        run: npm install write-good
      - run: write-good **/*.md